# Generated by Django 5.0.1 on 2024-05-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('number', models.CharField(max_length=11, verbose_name='Ваш номер телефона')),
                ('message', models.TextField(verbose_name='Обращение')),
            ],
            options={
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('kod_product', models.CharField(max_length=50, verbose_name='Код товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('cover', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
                ('info', models.TextField(max_length=1000, verbose_name='Информация о товаре')),
                ('structure', models.CharField(max_length=50, verbose_name='Состав букета')),
                ('massa', models.CharField(max_length=50, verbose_name='Вес')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата выставки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
