# Generated by Django 5.0.1 on 2024-02-17 14:25

import django.db.models.deletion
import mywork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('number', models.CharField(max_length=11, verbose_name='Ваш номер телефона')),
                ('message', models.TextField(verbose_name='Обращение')),
            ],
            options={
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('kod_product', models.CharField(max_length=50, verbose_name='Код товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('cover', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
                ('info', models.TextField(max_length=1000, verbose_name='Информация о товаре')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата выставки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(default=mywork.models.func, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('name', models.CharField(help_text='Введите имя и фамилию получателя', max_length=100, verbose_name='Имя и фамилия получателя')),
                ('adres', models.CharField(blank=True, help_text='Введите адрес доставки', max_length=200, verbose_name='Адрес')),
                ('number', models.CharField(help_text='Введите номер телефона получателя', verbose_name='Номер телефона получателя')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата заказа')),
                ('date_of_receipt', models.DateTimeField(verbose_name='Дата и время получения')),
                ('message', models.CharField(blank=True, help_text='Введите дополнительную информацию', max_length=200, verbose_name='Дополнительная информация')),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(help_text='Товар', on_delete=django.db.models.deletion.CASCADE, to='mywork.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
