# Generated by Django 5.0.1 on 2024-05-20 06:20

import cart.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mywork', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('session_key', models.CharField(blank=True, max_length=30, null=True)),
                ('tamestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(default=cart.models.func, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('name', models.CharField(help_text='Введите имя и фамилию получателя', max_length=100, verbose_name='Имя и фамилия получателя')),
                ('adres', models.CharField(blank=True, help_text='Введите адрес доставки', max_length=200, verbose_name='Адрес')),
                ('number', models.CharField(help_text='Введите номер телефона получателя', verbose_name='Номер телефона получателя')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата заказа')),
                ('date_of_receipt', models.DateTimeField(verbose_name='Дата и время получения')),
                ('message', models.CharField(blank=True, help_text='Введите дополнительную информацию', max_length=200, verbose_name='Дополнительная информация')),
                ('active', models.BooleanField(default=False, verbose_name='')),
                ('cart', models.ManyToManyField(blank=True, help_text='Товар', null=True, to='cart.cart', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
